version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      image: Dockerfile
    depends_on: 
      - backend
  backend:
    build:
      context: ./backend
      image: Dockerfile
